### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by syobocat** [DashieDev/DoggyTalentsNext#112]
My 1.18.2 server sometimes crashes with the following crashlog:

```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:322) ~[?:?] {re:mixin}
	at doggytalents.common.entity.accessory.BachWig$Inst.mayDropDisc(BachWig.java:59) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.accessory.BachWig$Inst.doAdditionalAttackEffects(BachWig.java:52) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.Dog.m_7327_(Dog.java:1848) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading,pl:runtimedistcleaner:A}
	at doggytalents.common.entity.ai.DogMeleeAttackGoal.checkAndPerformAttack(DogMeleeAttackGoal.java:300) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.ai.DogMeleeAttackGoal.m_8037_(DogMeleeAttackGoal.java:221) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at doggytalents.common.entity.ai.DogAiManager.tickRunningGoals(DogAiManager.java:289) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.ai.DogAiManager.tickRunning(DogAiManager.java:194) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.ai.DogAiManager.tickServer(DogAiManager.java:156) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading}
	at doggytalents.common.entity.Dog.m_8107_(Dog.java:825) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tacz.mixins.json:common.LivingEntityMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:create_enchantment_industry.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:310) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:AccessorMob,pl:mixin:A}
	at doggytalents.common.entity.Dog.m_8119_(Dog.java:581) ~[DoggyTalentsNext-1.18.2-1.18.32-patch1.jar%2361!/:1.18.32-patch1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```

Could you investigate it? (I have some other mods installed on the server, so it could be an compatibility issue, though)

**Comment by DashieDev** [comment]
Bugs confirmed, it will be fixed in the next release. 
The cause of the bug are Bach Wig, so a temporary solution is to not use the Bach Wig for now. We are sorry for the inconvinience.
