### ISSUE TITLE
Crash on Fabric with Dog bed

### ISSUE THREAD

**Issue by Kavaltheone** [DashieDev/DoggyTalentsNext#66]
Hello.
Minecraft 1.20.1, Fabric loader, DTN version 1.18.8 (fabric), no other mod installed except required:
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
fabric-api-0.88.1+1.20.1
When on creative mode in a newly created world try to see DTN tab game crashes:
```
Description: Rendering item

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/renderer/VanillaModelEncoder
	at doggytalents.client.block.model.DogBedModel.emitItemQuads(DogBedModel.java:254)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:127)
	at net.minecraft.class_918.handler$zie000$fabric-renderer-indigo$hook_renderItem(class_918.java:554)
	at net.minecraft.class_918.method_23179(class_918.java:125)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_481.method_2468(class_481.java:865)
	at net.minecraft.class_481.method_2389(class_481.java:775)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.renderer.VanillaModelEncoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
...
-- Item being rendered --
Details:
	Item Type: dog_bed
	Item Damage: 0
	Item NBT: {doggytalents:{beddingId:"minecraft:brown_wool",casingId:"minecraft:jungle_planks"}}
	Item Foil: false
```

When I've got wood and wool so unlocked a recipe of a Dog bed and got achievement game crashes with almost the same log, some minecraft methods differs and NBT of item rendered:
```
Description: Rendering item

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/renderer/VanillaModelEncoder
	at doggytalents.client.block.model.DogBedModel.emitItemQuads(DogBedModel.java:254)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:127)
	at net.minecraft.class_918.handler$zie000$fabric-renderer-indigo$hook_renderItem(class_918.java:554)
	at net.minecraft.class_918.method_23179(class_918.java:125)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51445(class_332.java:503)
	at net.minecraft.class_366.method_1986(class_366.java:48)
	at net.minecraft.class_374$class_375.method_2002(class_374.java:153)
	at net.minecraft.class_374.method_45074(class_374.java:36)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.class_374.method_1996(class_374.java:35)
	at net.minecraft.class_757.method_3192(class_757.java:972)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.renderer.VanillaModelEncoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
...
-- Item being rendered --
Details:
	Item Type: dog_bed
	Item Damage: 0
	Item NBT: null
	Item Foil: false
```
Also game crashes now when try to use crafting table ^_^

Also a not critical bug with displaying rice crop of any stage. Tried with no mods, with sodium, with sodium+indium - result the same
![2024-03-01_09 11 58](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/da04cc7a-ab95-4509-809f-ac3426224ade)

Full logs if needed for creative DTN tab and after achievement
[crash-2024-03-01_08.36.46-client.txt](https://github.com/DashieDev/DoggyTalentsNext/files/14459636/crash-2024-03-01_08.36.46-client.txt)
[crash-2024-03-01_09.12.54-client.txt](https://github.com/DashieDev/DoggyTalentsNext/files/14459640/crash-2024-03-01_09.12.54-client.txt)

**Comment by DashieDev** [comment]
Hmmm,  seems like your Fabric API version is outdated, which caused DTN to be missing a crucial class.
I wasn't aware that that mechanic was not present on API version before 0.92.0+1.20.1. I will update the mod to restrict the api version soon.
Try updating your Fabric API to newest.
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/5105683

Also for the crops, i seems to have not correctly registered the type for it. Will fix in the next update.

**Comment by Kavaltheone** [comment]
I made some test. In short - beds are working even on next Fabric API 0.89.0 but without Sodium+Indium or with version 0.5.3 Sodium and 1.0.27 Indium or higher. On prev version S 0.4.10 + I 1.0.21 (that only works with Create mod on Fabric) Dog Bed Tab displays but game crashes when putting bed on ground or new rice seed planting. It's Indium bug, because with only Sodium Dog bed displays and can be put on ground but no textures rendered (black nad magenta squares). And after crash (with Indium) you can load game and see empty transparent blocks on bed place and if Create mod presenton on rice place too.

So, issue can be closed because it works on Fabric API 0.89.0 or higher without Sodium. If Sodium needed it must be version 0.5.3 with Indium 1.0.27 or higher. Rice crops still need to check.

It would be great if DTN could work on previous versions of Sodium and Indium to play with Create and lots of other mods, but if it's impossible - it's ok. Anyway, your mod is AWESOME.

p.s. the crazy thing - Rice crop displays properly if Create mod installed but without Sodium+Indium ))  and without Create on later Sodium+Indium versions (0.5.3) rice crop transparent part fills not with white but yellow color 😵
![2024-03-04_11 21 51](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/844d7618-6586-4bd5-8dc0-4947fcf8ace6)
with Create mod and no Sodium
![2024-03-04_11 32 05](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/f5533a74-8e24-4e4f-94b6-a3e6813722d4)
with Create mod and no Sodium - look for rice and Dog bed
![2024-03-04_13 06 42](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/cf349a08-fb36-4cdc-ac5b-4aba272592ad)
Now Create with Sodium and Indium, early versions
![2024-03-04_13 09 22](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/e3d01270-6757-4b11-9e42-51aa0aef5597)
Only Sodium+Indium, early versions
![2024-03-04_13 12 39](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/3b12844c-0aaa-4022-a909-cd28b1db3891)

**Comment by DashieDev** [comment]
Ah seems like a couple of issues may or may not are out of DTN's control.....I will try my best to resolve them in the next update.
Forgive me since this is the first time i touched Fabric while porting DTN from forge, i just released it several days ago so it is still hot out of the oven, which mean it will stumbles a lot tbh 😅
Thanks a lot for testing the mod as we needs tester currently 😀

**Comment by Kavaltheone** [comment]
Since problem is not with mod but with old versions of Sodium, Indium and Fabric API, I'm closing issue.
Thanks for such a great mod!
